### ISSUE TITLE
Sugestão: Exemplo CREATE TABLE

### ISSUE THREAD

**Issue by lschlestein** [Herysson/Projeto-de-Banco-de-Dados#1]
No exemplo abaixo:
[https://github.com/Herysson/Projeto-de-Banco-de-Dados/Aula 7 - Instruções DDL - CREATE, ALTER e DROP.md](url)

Não chega a ser um problema, e sim uma observação.

Nesse exemplo, não é necessário utilizar NOT NULL, visto que quando se diz um atributo é uma PRIMARY KEY, já está dizendo que os valores desse atributo são Únicos e Não Vazios.
Sugestão:
```sql
CREATE TABLE Funcionario (
    FuncionarioID INT,
    Nome VARCHAR(100),
    Email VARCHAR(100),
    PRIMARY KEY (FuncionarioID)
);
```

**Comment by Herysson** [comment]
Realizada a alteração conforme observação.

Obrigado pela contribuição.

**Comment by Herysson** [comment]
Realizada a alteração conforme observação.

Obrigado pela contribuição.
